---
- name: Create protection policy
  hosts: localhost
  tasks:
    - name: Create new Protection Policy PP_name
      purestorage.fusion.fusion_pp:
        issuer_id: "{{ ansible_env.FUSION_ISSUER_ID }}"
        private_key_file: "{{ ansible_env.FUSION_PRIVATE_KEY_FILE }}"
        name: "PP_name"
        display_name: "PP_name"
        local_rpo: "15"  # in minutes
        local_retention: "24h"  # m(inutes), h(ours), d(ays), w(eeks) or y(ears)
        state: present  # or absent
